name: CCC
#version: 0.3.14 # version number, commit id, ... (optional)
origin: https://github.com/Fraunhofer-AISEC/cpg-contract-checker
info: CPG Contract Checker. Developed by Fraunhofer AISEC & ETH Zurich.
image: aisec/ccc
bin: scripts
solidity:
    entrypoint: "'$BIN/do_solidity.sh' '$FILENAME'"
